version: "3.7"

services:
  zipkin:
    image: openzipkin/zipkin
    container_name: ejc-zipkin
    ports:
      - "9411:9411"

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: ejc-graphite
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"

  grafana:
    image: grafana/grafana
    container_name: ejc-grafana
    depends_on:
      - graphite
    ports:
      - "3000:3000"

