version: "3.7"

services:
  zipkin:
    image: openzipkin/zipkin-slim:latest
    container_name: ejc-zipkin
    ports:
      - 9411:9411

  grafana:
    image: bitnami/grafana:latest
    container_name: ejc-grafana
    depends_on:
      - prometheus
      - influxdb
    ports:
      - 3000:3000
    volumes:
    - ./data/grafana:/opt/bitnami/grafana/data

  prometheus:
    image: bitnami/prometheus:latest
    container_name: ejc-prometheus
    depends_on:
      - prometheus-pushgateway
    ports:
      - 9090:9090
    volumes:
      - ./data/prometheus:/opt/bitnami/prometheus/data
      - ./config/prometheus:/opt/bitnami/prometheus/conf

  prometheus-pushgateway:
    image: prom/pushgateway:latest
    container_name: ejc-prometheus-pushgateway
    ports:
      - 9091:9091

  influxdb:
    image: bitnami/influxdb:latest
    container_name: ejc-influxdb
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_USER_PASSWORD: admin
      INFLUXDB_DB: ejc_database
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: user
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb:/bitnami/influxdb
